config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", :locale => /en|de/ do
		root  'pages#index'
		get   'favicon',    to: 'pages#favicon'
		match '/submit',    to: 'pages#submit', via: 'post'
		match '/merkle',    to: 'pages#merkle', via: 'post'
		match 'faq',        to: 'pages#faq',    via: 'get'
		match 'tsr',        to: 'pages#tsr',    via: 'get'
		match 'read_tsr',   to: 'pages#read_tsr',    via: 'get'
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :set_locale

	def default_url_options(options={})
		I18n.locale == :en ? {} : { locale: I18n.locale }
	end

	private

	def extract_locale_from_accept_language_header
		hal = request.env['HTTP_ACCEPT_LANGUAGE']
		if hal
			retval = hal.scan(/^[a-z]{2}/).first
			if "-en-de-".split(retval).count == 2
				retval
			else
				I18n.default_locale
			end
		else
			I18n.default_locale
		end
	end

	def set_locale
		I18n.locale = params[:locale] || extract_locale_from_accept_language_header
		Rails.application.routes.default_url_options[:locale]= I18n.locale
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	include ApplicationHelper
	
	require 'open3'
	
	def index
		@show_response = false
		@verify_only = false
		if !params[:hash].nil?
			@show_response = true
			@hash = params[:hash].to_s.strip
			if DateTime.now.utc.hour > 5
				my_time = DateTime.now.utc.end_of_day + 6.hours
			else
				my_time = DateTime.now.utc.beginning_of_day + 6.hours
			end
			@wait = (my_time.utc.to_i - Time.now.utc.to_i)/3600
			
			case ENV["BLOCKCHAIN"].to_s
			when "ARTIS"
				api_url = "https://artis.ownyourdata.eu/api/doc"
			else
				api_url = "https://blockchain.ownyourdata.eu/api/doc"
			end
			timeout = false
			begin
				if params[:operation].to_s == "verify"
					response = HTTParty.post(api_url,
						timeout: 25,
				        headers: { 'Content-Type' => 'application/json' },
				        body: { hash: @hash,
				        		mode: "verify" }.to_json ).parsed_response
				else
					response = HTTParty.post(api_url,
						timeout: 25,
				        headers: { 'Content-Type' => 'application/json' },
				        body: { hash: @hash }.to_json ).parsed_response
				end
			rescue
				timeout = true
			end
			if timeout
				flash[:warning] = t('general.service_unavailable')

			else
				if response["status"] == "unknown"
					@verify_only = true
					return
				else
					@id =          response["id"].to_s
					@address =     response["address"].to_s
					@root_node =   response["root-node"].to_s
					@audit_proof = response["audit-proof"].to_s
					@ether_ts =    response["dlt-timestamp"].to_s
					@oyd_ts =      response["oyd-timestamp"].to_s
					@tsr_ts =      response["tsr-timestamp"].to_s
					@tsr =         response["tsr"].to_s
					@did =         response["did"].to_s
					@history =     response["history"]
					@url =         response["url"].to_s
					@note =        response["note"].to_s
				end
			end
		end

		if params[:mode].to_s == "verify"
			@merkle_hash = params["merkle_hash"].to_s.strip
			@audit_proof_merkle = params["merkle_audit_proof"].to_s
			@root_node_merkle = ""

			if (@merkle_hash != "" && @audit_proof_merkle.to_s != "")
	            node = Digest::SHA256.digest("\0" + @merkle_hash)
	            ap = @audit_proof_merkle.split(", ")
	            ap.each do |item|
	            	item = item.strip
	                if item[0] == "+"
	                    item[0] = ""
	                    left_node = [item.strip].pack("H*")
	                    right_node = node
	                else
	                    item[0] = ""
	                    left_node = node
	                    right_node = [item.strip].pack("H*")
	                end
	                node = Digest::SHA256.digest("\x01" + left_node + right_node)
	            end
	            @root_node_merkle = node.unpack('H*')[0]
	        end
		end

	end

	def submit
		hash = params[:hash_field].to_s.strip
		if hash == ""
			hash = params[:hash_advanced].to_s.strip
		end
		if hash != ""
			case ENV["BLOCKCHAIN"].to_s
			when "ARTIS"
				api_url = "https://artis.ownyourdata.eu/api/doc"
			else
				api_url = "https://blockchain.ownyourdata.eu/api/doc"
			end
			response = HTTParty.post(api_url,
				timeout: 25,
	            headers: { 'Content-Type' => 'application/json' },
	            body: { hash: hash,
	                    mode: params[:api_mode] }.to_json )
			if response.code.to_s == "200"
				if response.parsed_response["status"].to_s == "unknown"
					flash[:success] = t('general.verification_success')
				else
					if params[:mode].to_s == "advanced"
						flash[:success] = t('general.success')
					else
						flash[:success] = t('general.success_basic')
					end
				end
			else
				flash[:warning] = t('general.hash_error')
			end
			if params[:mode].to_s == "advanced"
				redirect_to root_path(hash: hash, mode: "advanced", operation: params[:api_mode])
			else
				redirect_to root_path(hash: hash)
			end
		else
			if params[:mode].to_s == "advanced"
				redirect_to root_path(mode: "advanced")
			else
				redirect_to root_path
			end
		end
	end

	def merkle
		@my_hash = params[:hash_field_merkle].to_s.strip
		@my_audit_proof = params[:audit_proof_merkle].to_s
		
		redirect_to root_path(merkle_hash: @my_hash, merkle_audit_proof: @my_audit_proof, mode: "verify")
	end

	def faq
	end

	def tsr
		hash = params[:hash].to_s.strip
		if hash != ""
			case ENV["BLOCKCHAIN"].to_s
			when "ARTIS"
				api_url = "https://artis.ownyourdata.eu/api/doc"
			else
				api_url = "https://blockchain.ownyourdata.eu/api/doc"
			end
			response = HTTParty.post(api_url,
				timeout: 25,
	            headers: { 'Content-Type' => 'application/json' },
	            body: { hash: hash,
	                    mode: params[:api_mode] }.to_json )
			if response.code.to_s == "200"
				data = Base64.decode64(response.parsed_response["tsr"].to_s)
				file = "file.tsr"
				File.open(file, "wb"){ |f| f << data }
				send_file( file )
			else
				redirect_to root_path(hash: hash)
			end
		else
			redirect_to root_path(hash: hash)
		end
	end

	def read_tsr
		hash = params[:hash].to_s.strip
		if hash != ""
			case ENV["BLOCKCHAIN"].to_s
			when "ARTIS"
				api_url = "https://artis.ownyourdata.eu/api/doc"
			else
				api_url = "https://blockchain.ownyourdata.eu/api/doc"
			end
			response = HTTParty.post(api_url,
				timeout: 25,
	            headers: { 'Content-Type' => 'application/json' },
	            body: { hash: hash,
	                    mode: params[:api_mode] }.to_json )
			if response.code.to_s == "200"
				out, err, status = Open3.capture3("bash", "-c", 
                    'openssl ts -reply -in <(echo -n "' + response.parsed_response["tsr"].to_s + '" | base64 --decode) -text')
				render plain: out.to_s,
					   status: 200
			else
				redirect_to root_path(hash: hash)
			end
		else
			redirect_to root_path(hash: hash)
		end
	end

	def favicon
		send_file 'public/favicon.ico', type: 'image/x-icon', disposition: 'inline'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('general.title' + ENV["BLOCKCHAIN"].to_s) %></title>
    <%= csrf_meta_tags %>
  
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','<%= ENV["GOOGLE_TOKEN"] %>');</script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/sha256.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  </head>

  <body>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= ENV["GOOGLE_TOKEN"] %>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <div class="container">
      <div class="row">
        <div class="col-xs-2">
          <a href="https://www.ownyourdata.eu/<%= I18n.locale.to_s %>"><%= image_tag 'oyd.png', style: "height: 48px; margin: 18px 0;" %></a>
        </div>
        <div class="col-xs-8">
          <h1 style="text-align: center; margin-bottom: 30px;"><%= t('general.title' + ENV["BLOCKCHAIN"].to_s) %></h1>
        </div>
        <div class="col-xs-2" style="white-space: nowrap; margin-top: 30px; text-align: right;">
          <%= link_to_unless I18n.locale.to_s == "de", "DE", { locale: 'de', hash: params[:hash], mode: params[:mode], operation: params[:operation] } %> | 
          <%= link_to_unless I18n.locale.to_s == "en", "EN", { locale: 'en', hash: params[:hash], mode: params[:mode], operation: params[:operation] } %>
        </div>
      </div>
      <%= yield %>
    </div>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="margin: 0 0 30px;">
          &copy; <a href="https://www.ownyourdata.eu/<%= I18n.locale %>">OwnYourData.eu</a>
          <% if I18n.locale.to_s == "en" %>
            <a href="https://www.ownyourdata.eu/en/imprint/" style="margin: 0 10px;">Imprint</a>
            <a href="https://www.ownyourdata.eu/en/privacy-policy/">Privacy Policy</a>
          <% else %>
            <a href="https://www.ownyourdata.eu/de/impressum/" style="margin: 0 10px;">Impressum</a>
            <a href="https://www.ownyourdata.eu/de/datenschutz/">Datenschutz</a>
          <% end %>
          <%= link_to t('general.faq'), faq_url(locale: I18n.locale), style: "margin: 0 10px;" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/_docs.de.html.erb
<h4 style="margin: 45px 0 -25px;">Klicke auf das jeweilige Thema, um weitere Informationen zu erhalten.</h4>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" style="margin-top: 40px;">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="blockchain_general">
      <h2 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Über die Blockchain
        </a>
      </h2>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="blockchain_general">
      <div class="panel-body">
        <p>Die Blockchain sind kryptographisch miteinander verbundene und dezentral gespeicherte Datensätze. Jeder Datensatz enthält dabei einen Fingerabdruck (Hashwert) des vorhergehenden Datensatzes, einen Zeitstempel und weitere Transaktionsdaten. Dadurch, dass spätere Datensätze auf früheren Datensätzen aufbauen und diese damit als richtig bestätigen, ist es unmöglich diese früheren Daten zu ändern oder zu löschen, ohne alle darauf aufbauenden Daten ebenfalls zu ändern. Eine solche Änderung ist aber durch die verteilte Speicherung der Daten nicht möglich und würde sofort erkannt werden.</p>
        <p>Beim Versiegeln von Dokumenten wird diese Eigenschaften der garantierten Datenintegrität einer Blockchain verwendet.</p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="blockchain_open_source">
      <h2 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Freier und quell-offener Blockchain Dienst
        </a>
      </h2>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="blockchain_open_source">
      <div class="panel-body">
        <p>Der Verein zur Förderung der selbstständigen Nutzung von Daten hat es sich zum Ziel gesetzt, die selbstbestimmte Nutzung persönlicher Daten durch Privatpersonen zu fördern. Die Blockchain-Technologie ermöglicht nun auch für die private Datennutzung einen einfachen und sicheren Weg zum Nachweis von Datenintegrität und daher bietet der Verein dieses Service an. Durch die Kombination von mehreren Vorgängen - derzeit erfolgt die Gruppierung pro Tag - können die dafür notwendigen Transaktionskosten gering gehalten werden und sind durch das Vereinsbudget abgedeckt.</p>
        <p>Auf Github ist der Quellcode für diese Webseite unter der MIT-Lizenz frei verfügbar: <a href="https://github.com/OwnYourData/app-seal">https://github.com/OwnYourData/app-seal</a></p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="blockchain_api">
      <h2 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Blockchain API
        </a>
      </h2>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="blockchain_api">
      <div class="panel-body">
        <p>Der Dienst zum Versiegeln von Dokumenten verwendet im Hintergrund eine frei zugängliche API, die ebenfalls von anderen Diensten genutzt werden kann. Mittels HTTP POST Request kann ein Hashwert sowohl in die Blockchain geschrieben werden, oder - wenn der Hashwert zuvor bereits verwendet wurde - wird die Adresse in der Blockchain zurückgegeben. Da alle Hashwerte eines Tages in einem Merkle-Baum kombiniert werden, ist neben der Adresse in der Blockchain auch der Audit-Proof wie in <a href="https://tools.ietf.org/html/rfc6962">RFC 6962</a> angegeben.</p>
        <p>Diese API ist mittels Swagger hier beschrieben (nur in englischer Sprache): <a href="https://blockchain.ownyourdata.eu/doc">https://blockchain.ownyourdata.eu/doc</a><br>
        Auf Github ist der Quellcode für das API-Service unter der MIT-Lizenz frei verfügbar:</p>
        <ul>
          <li>High-level API: <a href="https://github.com/OwnYourData/api-blockchain">https://github.com/OwnYourData/api-blockchain</a></li>
          <li>Blockchain Service: <a href="https://github.com/OwnYourData/srv-blockchain">https://github.com/OwnYourData/srv-blockchain</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="blockchain_api_samples">
      <h2 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Blockchain API Beispiele
        </a>
      </h2>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="blockchain_api_samples">
      <div class="panel-body">
        <p>Verwende den folgenden Aufruf, um einen Hashwert mittels API in der Blockchain zu speichern:<br>
          <pre>$ curl -X POST "https://blockchain.ownyourdata.eu/api/doc?hash=006748c21efaf8fe67b833d82cba7955619c3c3b06e11ed6562fbf6a1cb06f2c"</pre></p>
        <p>Beim ersten Aufruf wird folgende JSON-Struktur als Rückgabewert geliefert:<br>
          <pre>{
  "status": "new",
  "address": "",
  "root-node": "",
  "audit-proof": [],
  "ether-timestamp": "",
  "oyd-timestamp": "2018-09-01T22:39:16Z"
}</pre></p>
        <p>Sobald alle eingegangenen Hashwerte eines Tages tatsächlich in die Blockchain geschrieben wurden, enthält der Rückgabewert folgende weitere Informationen:<br>
          <pre>{
  "status": "exist",
  "address": "0xcf4a0cf4b9ea6d10c0407680fe1f73df1a59c362db29a1863e14d85fcdb69c9c",
  "root-node": "10611bc55c740b46517ce15ad82b79350468affc4660379771475eaa494ec3fd",
  "audit-proof": "+661eec906b6a88b3bf751d7f5c62b84de03fadaed78e9398efebf408b2a3236c,
                  -0cdf07531250367444ae8a3bfcbb0b928e1313ece65f2a45abcc2226e278d6cd,
                  -5cbe1017c15d83ce8f4c02b4c1d8d2fa0c51bbe281363d98ef7dc33ffe26a072",
  "ether-timestamp": "2018-09-02T06:00:17Z",
  "oyd-timestamp": "2018-09-01T22:39:16Z"
}</pre></p>
        <p>Anmerkung: die Vorzeichen (+,-) im Feld <code>audit-proof</code> geben an, ob der jeweilige Hashwert als linker (+) oder rechter (-) Knoten bei der Überprüfung zur Berechnung des Wurzelknotens zu betrachten ist - siehe <a href="https://tools.ietf.org/html/rfc6962">RFC 6962</a>. Als Hashfunktion wird generell SHA256 verwendet.</p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="merkle_tree">
      <h2 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Über Merkle Bäume
        </a>
      </h2>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="merkle_tree">
      <div class="panel-body">
        <p>Ein Merkle-Baum ist eine sogenannter Binärbaum, d.h., jeder Knoten besitzt höchstens 2 Kindknoten. Die Blätter sind dabei Hash-Werte und jeweils 2 benachbarte Knoten bilden einen übergeordneten Knoten. Der Hash-Wert eines Blattes, gemeinsam mit dem Audit-Proof (lt. <a href="https://tools.ietf.org/html/rfc6962">RFC 6962</a>) ergibt eindeutig die Wurzel des Merkle-Baums. Wichtig ist bei der Anwendung des Audit-Proofs die Angabe, ob es sich jeweils um den linken oder rechten Knoten im Pfad handelt.</p>
        <p>In der vorliegenden Implementierung werden die Werte des Audit-Proofs durch + (linker Knoten) und - (rechter Knoten) gekennzeichnet. Gemeinsam mit dem Hashwert kann so der Wurzelknoten berechnet werden. Das Verfahren des Merkle Baums wird verwendet, um alle eingegangen Hash Werte eines Tages in eben diesem Binärbaum anzuordnen und dann nur den Wurzelknoten selbst in der Blockchain zu speichern.</p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="trusted_timestamp">
      <h2 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Über vertrauenswürdige Zeitstempel
        </a>
      </h2>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="trusted_timestamp">
      <div class="panel-body">
        <p>Vertrauenswürdiges Zeitstempeln ist ein Prozess, bei dem Datum und Zustand eines Dokuments sicher verfolgt werden können. Sicherheit bedeutet hier, dass niemand - nicht einmal der Besitzer des Dokuments - in der Lage ist, den Zeitstempel nach der Erstellung zu ändern. Der hier angebotene Zeitstempel folgt dem Standard <a href="https://www.ietf.org/rfc/rfc3161.txt" target="_blank">RFC 3161</a> und kann auf zeitsensible Transaktionen durch unabhängig verifizierte und überprüfbare Datums- und UTC-Koordinaten (Coordinated Universal Time) angewendet werden.</p>
        <p>Das Hinzufügen eines vertrauenswürdigen Zeitstempels zu einem Dokument bietet ein digitales Siegel für die Datenintegrität und ein vertrauenswürdiges Datum und die Uhrzeit, zu der die Transaktion stattgefunden hat. Empfänger von Dokumenten mit einem vertrauenswürdigen Zeitstempel können überprüfen, wann das Dokument oder der Code digital signiert wurde, sowie überprüfen, ob das Dokument oder der Code nach dem Datum, für das der Zeitstempel gilt, geändert wurde.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/faq.de.html.erb
<%= link_to t('general.back'), "/" + I18n.locale.to_s + "/" %>
<h2>Häufige Fragen</h2>

<h4>Warum ist dieses Service gratis?</h4>
Der <em>Verein zur Förderung der selbstständigen Nutzung von Daten</em> bietet diesen Service kostenlos an, damit jeder von der Blockchain-Technologie profitieren kann.

<h4>Gibt es eine API, um gratis Werte in die Blockchain zu schreiben?</h4>
Ja, die Beschreibung ist hier verfügbar: <a href="https://blockchain.ownyourdata.eu/doc">https://blockchain.ownyourdata.eu/doc</a>

<h4>Ist der Quellcode für dieses Service verfügbar?</h4>
Ja, der grundlegende Service zum Lesen und Schreiben der Blockchain ist hier verfügbar: <a href="https://github.com/OwnYourData/service-blockchain">Github</a> (<a href="https://hub.docker.com/r/oydeu/srv-blockchain/">Docker image</a>)<br>
die high-level API: <a href="https://github.com/OwnYourData/api-blockchain">Github</a> (<a href="https://hub.docker.com/r/oydeu/api-blockchain/">Docker image)</a><br>
diese Webseite: <a href="https://github.com/OwnYourData/app-seal">Github</a> (<a href="https://hub.docker.com/r/oydeu/app-seal/">Docker image)</a>

<p>&nbsp;</p>
<p><%= link_to t('general.back'), "/" + I18n.locale.to_s + "/" %></p>

app/views/pages/faq.en.html.erb
<%= link_to t('general.back'), "/" + I18n.locale.to_s + "/" %>
<h2>Frequently Asked Questions</h2>

<h4>Why is this service free?</h4>
The <em>Public Charity to foster personal use of data</em> offers this service for free to enable everyone to benefit from blockchain technology.

<h4>Is there an API for writing values to the blockchain for free?</h4>
Yes, the documentation is available here: <a href="https://blockchain.ownyourdata.eu/doc">https://blockchain.ownyourdata.eu/doc</a>

<h4>Is the source code for this service available?</h4>
Yes, the basic service to read and write from the blockchain is available here: <a href="https://github.com/OwnYourData/service-blockchain">Github</a> (<a href="https://hub.docker.com/r/oydeu/srv-blockchain/">Docker image</a>)<br>
the high-level API: <a href="https://github.com/OwnYourData/api-blockchain">Github</a> (<a href="https://hub.docker.com/r/oydeu/api-blockchain/">Docker image)</a><br>
this web page: <a href="https://github.com/OwnYourData/app-seal">Github</a> (<a href="https://hub.docker.com/r/oydeu/app-seal/">Docker image)</a>

<p>&nbsp;</p>
<p><%= link_to t('general.back'), "/" + I18n.locale.to_s + "/" %></p>